/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import java.io.*;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author alan.ryan
 */
public class ClientFrame extends javax.swing.JFrame {

    String cardNumber;
    String expiryDate;
    String cardType;
    String cardHolderName;
    String cvvString;
    int cvv;
    boolean isValidCard;
    
    // IP address of the server
    static String serverIP = "localhost";

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
    } //end ClientFrame init method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        cardNumberLabel = new javax.swing.JLabel();
        cardNumberTextfield = new javax.swing.JTextField();
        expiryDateLabel = new javax.swing.JLabel();
        dateTextfield = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        cvvTextfield = new javax.swing.JTextField();
        cardNameLabel = new javax.swing.JLabel();
        cardNameTextfield = new javax.swing.JTextField();
        cardTypeLabel = new javax.swing.JLabel();
        cardTypeCombo = new javax.swing.JComboBox();
        buttonPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        testMaster_btn = new javax.swing.JButton();
        testVisa_btn = new javax.swing.JButton();
        french_btn = new javax.swing.JButton();
        eng_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credit Card Validator");

        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Input Your Details"));
        inputPanel.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        cardNumberLabel.setText("Enter Card Number");
        inputPanel.add(cardNumberLabel);

        cardNumberTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTextfieldActionPerformed(evt);
            }
        });
        inputPanel.add(cardNumberTextfield);

        expiryDateLabel.setText("Enter Expiry Date");
        inputPanel.add(expiryDateLabel);

        dateTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextfieldActionPerformed(evt);
            }
        });
        inputPanel.add(dateTextfield);

        cvvLabel.setText("Enter CVV");
        inputPanel.add(cvvLabel);
        inputPanel.add(cvvTextfield);

        cardNameLabel.setText("Enter Card Name");
        inputPanel.add(cardNameLabel);
        inputPanel.add(cardNameTextfield);

        cardTypeLabel.setText("Enter Card Type");
        inputPanel.add(cardTypeLabel);

        cardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laser", "Visa", "Mastercard" }));
        cardTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTypeComboActionPerformed(evt);
            }
        });
        inputPanel.add(cardTypeCombo);

        getContentPane().add(inputPanel, java.awt.BorderLayout.CENTER);

        submitButton.setBackground(new java.awt.Color(153, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(submitButton);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(clearButton);

        testMaster_btn.setText("TEST Mast");
        testMaster_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMaster_btnActionPerformed(evt);
            }
        });
        buttonPanel.add(testMaster_btn);

        testVisa_btn.setText("TEST Visa");
        testVisa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testVisa_btnActionPerformed(evt);
            }
        });
        buttonPanel.add(testVisa_btn);

        french_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/france.png"))); // NOI18N
        buttonPanel.add(french_btn);

        eng_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/united_kingdom.png"))); // NOI18N
        buttonPanel.add(eng_btn);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardNumberTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cardNumberTextfieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Create a new Credit Card object
        // send it to the server
        
        try {
            // Establish connection with the server
            Socket socket = new Socket("localhost", 8111);

            // Create an output stream (with the object) to the server
            ObjectOutputStream toServer = new ObjectOutputStream(socket.getOutputStream());
        
            CreditCard card = newCard(); // new instance of CredicatCard to send to Server

            // Send CreditCard object to the server
            toServer.writeObject(card);
            
            System.out.println("new Credit Card details Sent To Server");
            
            // stream to receive Boolean response from Server
            DataInputStream validCardInputStream = new DataInputStream(socket.getInputStream());
            isValidCard = validCardInputStream.readBoolean(); //from Server
            String output = "";
            
            if(isValidCard == true){
                output = "valid";
            }
            else output = "invalid";
            
            JOptionPane.showMessageDialog(null,"Card is  " + output);

      }//end try
      
      catch (IOException ex)  {
        System.err.println(ex);
      }//end catch
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void dateTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateTextfieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // Clear all text input fields
        cardNumberTextfield.setText("");
        dateTextfield.setText("");
        cardNameTextfield.setText("");
        cardTypeCombo.setSelectedIndex(0); //Laser
        cvvTextfield.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void testMaster_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testMaster_btnActionPerformed
        // set pre-built Laser Credit Card 
        cardNumberTextfield.setText("5555555555554444");
        dateTextfield.setText("0320"); //MySQL takes YYYY-MM-DD, CreditCards are in mmyy
        cardTypeCombo.setSelectedIndex(2); //Master
        cardTypeCombo.getSelectedItem().toString(); //default is Laser
        cardNameTextfield.setText("John Smith"); 
        cvvTextfield.setText("457");
    }//GEN-LAST:event_testMaster_btnActionPerformed

    private void testVisa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testVisa_btnActionPerformed
        // set pre-built Visa Credit Card  (don't forget to select Visa from combobox)
        cardNumberTextfield.setText("4222222222222");
        dateTextfield.setText("0320"); //MySQL takes YYYY-MM-DD, CreditCards are in mmyy
        cardTypeCombo.setSelectedIndex(1); //Visa
        cardTypeCombo.getSelectedItem().toString(); //default is Laser
        cardNameTextfield.setText("John Smith"); 
        cvvTextfield.setText("578");
    }//GEN-LAST:event_testVisa_btnActionPerformed

    private void cardTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTypeComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel cardNameLabel;
    private javax.swing.JTextField cardNameTextfield;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JTextField cardNumberTextfield;
    private javax.swing.JComboBox cardTypeCombo;
    private javax.swing.JLabel cardTypeLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextfield;
    private javax.swing.JTextField dateTextfield;
    private javax.swing.JButton eng_btn;
    private javax.swing.JLabel expiryDateLabel;
    private javax.swing.JButton french_btn;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton testMaster_btn;
    private javax.swing.JButton testVisa_btn;
    // End of variables declaration//GEN-END:variables
    
    
    /*------------------------*/
    // new Credit Card from User entries
    /*------------------------*/
    public CreditCard newCard(){
        //get details from input textfields
        cardNumber = cardNumberTextfield.getText();
        expiryDate = dateTextfield.getText();
        cardType = cardTypeCombo.getSelectedItem().toString();
        cardHolderName = cardNameTextfield.getText();
        int cardNumberLength = cardNumber.length();
        
        cvvString = cvvTextfield.getText();
        cvv =  Integer.parseInt(cvvString);
        
        if ( (cardNumberLength ==13) || (cardNumberLength ==16) || (cardNumberLength ==19) ){
            System.out.println( "Card Holder Name: " + cardHolderName + 
                                "\nCard Number : " + cardNumber +
                                "\nCard number length : " + cardNumberLength +
                                "\nCard expiry Date : " + expiryDate +
                                "\nCard Type : " + cardType +
                                "\nCard CVV : " + cvv );
        }
        
        // constructor for new CreditCard
        CreditCard newCard = new CreditCard(cardNumber,expiryDate,cardType,cardHolderName, cvv);
        return newCard; //will send this object to Server for validation
    }

} //end ClientFrame
